### ISSUE TITLE
List of Object as Input in Mutation

### ISSUE THREAD

**Issue by zerounix** [graphql-java/graphql-java-tools#41]
Hi,

i have a question about parameter passing in a mutation.

My schema looks something like this:

```
input KeyValuePairInput {
    key: String!
    value: String!
    valueType: ValueTypeEnum
}
enum ValueTypeEnum {
    Int
    Float
    String
    Boolean
}
```

with a Mutation and a method in it:
```
someFunction(
        name: String!
        key: String
        variables: [KeyValuePairInput]
    ): SomeReturn
```

The corresponding Resolver for my Mutation has a public method

```
public class Mutation implements GraphQLRootResolver {
..
    public SomeReturn someFunction(String name, String key, ArrayList<KeyValuePairInput> variables) {}
}
```

Now when a call the mutation, the Java method gets called, but the type of the variables is ArrayList<LinkedHashMap>. Am i missing something here? I expected it to be ArrayList<KeyValuePairInput>.

Sorry if the question is stupid, but i can't find a solution to this problem.

**Comment by apottere** [comment]
> but the type of the variables is ArrayList. Am i missing something here? I expected it to be ArrayList

I think there's a typo here.  What's the question?

**Comment by zerounix** [comment]
Ah, sorry, i think markdown killed it. So the actual type is `ArrayList<LinkedHashMap>` and i expected `ArrayList<KeyValuePairInput>` .

**Comment by apottere** [comment]
That's odd, jackson should be transforming it to an ArrayList<KeyValuePairInput> if it can.  Are you using `3.2.0`?

**Comment by apottere** [comment]
I just realized I forgot to update the readme with the new version, but it's in the "maven central" badge

**Comment by zerounix** [comment]
I used version 2.1.3. I just updated the dependency to latest 2.3.0. Now on startup i get 
`Caused by: java.lang.NoSuchMethodError: graphql.schema.GraphQLSchema.getDictionary()Ljava/util/Set;`

**Comment by zerounix** [comment]
I update from 2.1.3 to 3.2.0, and on startup i get

`org.camunda.bpm.engine.task.Task.processInstance( [, graphql.schema.DataFetchingEnvironment])`

which is another Query implementation in the code. I boot the application with

`SchemaParser.newParser()
                .file("stuff.graphqls")
                .resolvers(resolvers)
                .dictionary(
                        KeyValuePairInput.class,
                        KeyValuePair.class,
                        ....
                        ValueTypeEnum.class
                )
                .build()
                .makeExecutableSchema();`

I guess something changed?

**Comment by apottere** [comment]
What's the full exception?

**Comment by zerounix** [comment]
I guess i'm missing a resolver here. The strange thing is, it used to work with 2.1.3.

`Caused by: com.coxautodev.graphql.tools.ResolverError: No method found with any of the following signatures (in priority order):
  org.camunda.bpm.engine.task.Task.processInstance( [, graphql.schema.DataFetchingEnvironment])
  org.camunda.bpm.engine.task.Task.getProcessInstance( [, graphql.schema.DataFetchingEnvironment])
	at com.coxautodev.graphql.tools.Resolver.getDataClassMethod(Resolver.kt:76)
	at com.coxautodev.graphql.tools.NoResolver.getMethod(Resolver.kt:144)
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanObjectForDictionaryItems(SchemaClassScanner.kt:192)
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanForClasses(SchemaClassScanner.kt:113)
	at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:107)
	at org.camunda.bpm.extension.graphql.GraphQLServer.graphQLSchema(GraphQLServer.java:67)
	at org.camunda.bpm.extension.graphql.GraphQLServer$$EnhancerBySpringCGLIB$$8ebb32b5.CGLIB$graphQLSchema$0(<generated>)
	at org.camunda.bpm.extension.graphql.GraphQLServer$$EnhancerBySpringCGLIB$$8ebb32b5$$FastClassBySpringCGLIB$$56394102.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at org.camunda.bpm.extension.graphql.GraphQLServer$$EnhancerBySpringCGLIB$$8ebb32b5.graphQLSchema(<generated>)
	at sun.reflect.GeneratedMethodAccessor269.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 62 more`

If you like, you can find the code here: https://github.com/camunda/camunda-bpm-graphql
Just change the version in the pom.xml.

**Comment by apottere** [comment]
How can I run this?  I tried the sprint-boot main class but I don't have the camunda engine classes (marked provided).

**Comment by apottere** [comment]
Nevermind, I commented things out till it got to the graphql-java-tools error :)

**Comment by apottere** [comment]
Ah, the issue comes from here:
```java
public Task setAssignee(String taskEntityId, String assignee)
```

In graphql-java-tools 3.x, it scans the resolver methods to find the class name/type name map, and the graphql definition for that field looks like this:
```
    setAssignee(
        taskEntityId: String!
        assignee: String!
    )
    : TaskEntity
```

graphql-java-tools assumes that means that the graphql type `TaskEntity` corresponds to the java type `Task`, since they're used in the same place.  This was allowed in 2.x because it was less stringent, but required you to provide all classes you wanted to use.  This resolver method would blow up at runtime if you returned anything other than a `TaskEntity` in 2.x.

That being said, I'll update the library to be clearer about it's assumptions when finding resolver methods so it's clear it found the wrong mapping.
